theme: jekyll-theme-cayman
include: ["_pages"]
defaults:
  # _pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Site Settings
locale                   : "de-DE"
title                    : "Pencak Silat Bongkot Harimau"
title_separator          : "-"
name                     : &name "Pencak Silat Bongkot Harimau Deutschland Hamburg"
description              : &description "Informationen ueber Pencak Silat Bongkot Harimau in Hamburg"
breadcrumbs              : true
show_downloads           : true