theme: minimal-mistakes-jekyll
include: ["_pages"]
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

# Site Settings
locale                   : "de-DE"
title                    : "Pencak Silat Bongkot Harimau"
title_separator          : "-"
name                     : &name "Pencak Silat Bongkot Harimau Deutschland Hamburg"
description              : &description "Informationen ueber Pencak Silat Bongkot Harimau in Hamburg"
breadcrumbs              : true