theme: jekyll-theme-cayman
include: ["_pages"]
defaults:
  # _pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Site Settings
baseurl: "/"
locale: "de-DE"
title: "Pencak Silat Bongkot Harimau"
title_separator: "-"
name: &name "Pencak Silat Bongkot Harimau Deutschland Hamburg"
description: &description "Informationen über Pencak Silat Bongkot Harimau in Hamburg"
breadcrumbs: true
show_downloads: false
sass:
  sass_dir: assets/css
